# Generated by Django 4.2.4 on 2023-12-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendsrequestmodel_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendsrequestmodel',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
