# Generated by Django 4.2.4 on 2023-12-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friendsrequestmodel_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendsrequestmodel',
            old_name='seen',
            new_name='accepted_seen',
        ),
        migrations.AddField(
            model_name='friendsrequestmodel',
            name='request_seen',
            field=models.BooleanField(default=False),
        ),
    ]
