# Generated by Django 4.2.4 on 2024-01-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_friendsrequestmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendsrequestmodel',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
