# Generated by Django 4.2.1 on 2023-09-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Charts', '0003_weeklyjurnalmodel_calendarimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarimagemodel',
            name='jurnal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Charts.weeklyjurnalmodel'),
        ),
    ]
