# Generated by Django 4.2.4 on 2023-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_calendarimagemodel_jurnal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('1', 'Call săptămânal - Structură de decizie "if" / "else"'), ('2', 'Call săptămânal - Structuri repetitive "while" / "for"'), ('3', 'Call săptămânal - "Șiruri de numere"'), ('4', 'Call săptămânal - "Matrice (Tablouri bidimensionale)"'), ('5', 'Call săptămânal - Mindset'), ('6', 'Call săptămânal - Simulări de interviuri'), ('7', 'Call săptămânal - Proiecte personale')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='weeklyjurnalmodel',
            name='select_call',
        ),
        migrations.AddField(
            model_name='weeklyjurnalmodel',
            name='select_call',  
            field=models.ManyToManyField(to='charts.choices'),
        ),
    ]
