# Generated by Django 4.2.4 on 2023-09-21 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Charts', '0005_choices_remove_weeklyjurnalmodel_select_call_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyJurnalModel',
            new_name='WeeklyJournalModel',
        ),
        migrations.RenameField(
            model_name='calendarimagemodel',
            old_name='jurnal',
            new_name='journal',
        ),
    ]
