# Generated by Django 4.2.1 on 2023-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_rename_weeklyjurnalmodel_weeklyjournalmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarimagemodel',
            name='calendar',
            field=models.ImageField(upload_to='charts/images'),
        ),
    ]  
  