# Generated by Django 4.2.1 on 2023-09-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_alter_calendarimagemodel_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarimagemodel',
            name='calendar',
            field=models.ImageField(upload_to='Charts/images'),
        ),
    ]
