# Generated by Django 4.2.4 on 2024-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_alter_calendarimagemodel_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='description',
            field=models.CharField(choices=[('1', 'Weekly Call - Decision Structure "if" / "else"'), ('2', 'Weekly Call - Repetitive Structures "while" / "for"'), ('3', 'Weekly Call - Number Arrays'), ('4', 'Weekly Call - Matrices (Two-Dimensional Arrays)'), ('5', 'Weekly Call - Mindset'), ('6', 'Weekly Call - Interview Simulations'), ('7', 'Weekly Call - Personal Projects')], max_length=100),
        ),
    ]
